### ISSUE TITLE
How to obtain ActiveDirectoryTenant & ActiveDirectoryClientAppId

### ISSUE THREAD

**Issue by toryb** [Microsoft/Dynamics-AX-Integration#1]
In your sample you have the ActiveDirectoryTenant & ActiveDirectoryClientAppId hard coded for your deployment. How do I obtain those values for my deployment?

Thanks,

Tory

**Comment by SorenSparso** [comment]
Hi,

Has this been answered? I am having the same issue.

Thanks,

Soren

**Comment by nimakms** [comment]
Hi Tory, 

Apologies for the delay in response, I was not notified of the opened issue. The following link should provide enough information for obtaining these values for the specific tenant used with your AX instance: https://ax.help.dynamics.com/wiki/dynamics-ax-7-services-technical-concepts-guide/

Regards,
Nima

**Comment by nimakms** [comment]
Closing due to no response.

**Comment by jamesnovak** [comment]
I am also trying to find the attributes required by the AuthenticationUtility:
            ActiveDirectoryResource
            ActiveDirectoryTenant
            ActiveDirectoryClientAppId
            ActiveDirectoryClientAppSecret
Unfortunately, the link provided in the previous comment now redirects so I cannot seem to find the info.  I have been reviewing this section, but I am stumped.  
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/data-entities/services-home-page

Can anyone provide some instructions on where to find these value?

**Comment by srpraveenkumar** [comment]
Hi James, 

   The following wiki has pointers on how to get these. 
https://github.com/Microsoft/Recurring-Integrations-Scheduler/wiki

**Comment by jamesnovak** [comment]
Thanks for the information!  That will be a big help.  I was actually able to get things working this AM using the following link: https://blogs.msdn.microsoft.com/axsupport/2017/07/13/recurring-integrations-in-dynamics-365-for-operations/

Ironically, it was posted in the comments in the link I included in my previous comment.  "This article is outdated and made me waste a ton of time trying to get it to work. Refer to this blogpost for proper and updated information: ... Specifically the piece on the Azure App registration is wrong and missing steps."

Thanks again for the fast reply!
