### ISSUE TITLE
Processing completed with errors for job:

### ISSUE THREAD

**Issue by Sharran** [Microsoft/Dynamics-AX-Integration#10]
Hi,

Getting the below error in the Error log file:
{"DataJobStatus":{"DataProject":"XX","DataJobIdentifier":"18e5833c-bbf2-4287-a63b-f8b6dbbbe6ea","ExternalIdentifier":"XX.xlsx","ExecutionIdentifier":"XXImport-2016-08-27T20:58:15-319F6ED28C6D4756AC9F4D4E312DC4F9","DataJobStartedDateTime":"2016-08-27T20:58:15","DataJobCompletedDateTime":"2016-08-27T20:58:15","DataJobState":8},"ExecutionLog":"","ExecutionDetail":null}

Could you also let me know how to configure 
"A native client app that has permissions setup for Dynamics Connector APIs.". All i Could see is "Dynamics ERP".

kindly suggest.

Regards
SS

**Comment by nimakms** [comment]
Hi, You can find instructions here under "Register a native application with AAD": https://ax.help.dynamics.com/wiki/dynamics-ax-7-services-technical-concepts-guide/ 
.

**Comment by Sharran** [comment]
Hi,

I have registered the native application as described in AX wiki, I was not able to find the Dynamics connector API in Azure, do I need to create a new API in Azure and then provide access to it in my Native Application. So that i won't get the above stated error.

Regards
Sharran

**Comment by Sharran** [comment]
Hi,

Checked in the permission category of Dynamics ERP, was not able to find "Dynamics Connector APIs.", 
Any suggestions on this.
Regards
SS

**Comment by RaphaelTagliani** [comment]
Dear Sharran,

Apparently, the MS tutorial is not up-to-date, the choices I have in the native app are :

Access Dynamics AX online as organization users
Access Dynamics AX data
Access Dynamics AX Custom Service

I checked them all, and my call to the OData endpoint is working.

**Comment by Sharran** [comment]
the problem was with the job status API, commented out the code and it worked fine.
Do we have any application from MS for Dequeue recurring Job.
