### ISSUE TITLE
System.IO.FileLoadException

### ISSUE THREAD

**Issue by jwolber** [Microsoft/Dynamics-AX-Integration#11]
Exception on line 75 of DefaultDataFlowNetwork.cs:

An exception of type 'System.IO.FileLoadException' occurred in RecurringIntegrationApp.exe but was not handled in user code

Additional information: Could not load file or assembly 'Microsoft.Dynamics.AX.Framework.Tools.DataManagement.Serialization, Version=0.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

**Comment by jwolber** [comment]
Replacing the Microsoft.Dynamics.AX.Framework.Tools.DataManagement.Serialization.dll included in the repository/solution with the version that was in "J:\AosService\WebRoot\bin" on an AX7 dev box running Update 1 resolved the issue. The new assembly was 8KB larger in size so I assume there was some code change or reference added that resolved this issue.

**Comment by gregsdennis** [comment]
@jwolber any chance you can share the file?  (Don't violate any licenses.)

**Comment by benson172** [comment]
@jwolber can you share the AX build version # and the .dll file version # that worked for you? thx.

**Comment by srpraveenkumar** [comment]
This dll is present in your dev boxes as jwolber mentioned. 

Kindly replace the dll with that of the version of product you are using.
Typically you will find the dll in K:\AosService\WebRoot\bin on your Tier 1 Dev box.

**Comment by fhburney** [comment]
so replacing the.dll did not fixed it for me

I wrote my own JSON classes for Deserialization the data from the job status check methods.

**Comment by gregsdennis** [comment]
@fhburney if you could share those in a gist or something, you'd be a hero.

**Comment by johnxy84** [comment]
Can anybody share any possible solutions? Currently Facing this Issue.
