### ISSUE TITLE
authority_not_in_valid_list error

### ISSUE THREAD

**Issue by kim82** [Microsoft/Dynamics-AX-Integration#2]
I'v entered UriString/UserName/Password/ADResource/ADTenant/ADClientAppId in the ClientConfiguration,

When I run the JsonConsoleApplication I get the following error:
Additional information: authority_not_in_valid_list: 'authority' is not in the list of valid addresses

**Comment by nimakms** [comment]
Hi Kim, 

Apologies for the delay in response, I was not notified of the opened issue.

The error is coming from the Azure Active Directory library. it indicates that the tenant you entered is not correct. Authority is usually in the form of https://login.windows.net/yourtenant.onmicrosoft.com. Ensure this is correct.

The following link should provide enough information for obtaining these values for the specific tenant used with your AX instance: https://ax.help.dynamics.com/wiki/dynamics-ax-7-services-technical-concepts-guide/

Regards,
Nima

**Comment by nimakms** [comment]
Closing issue since there was no response.
