### ISSUE TITLE
Microsoft.Dynamics.DataEntities.GetAzureWriteUrl

### ISSUE THREAD

**Issue by Krishnc** [Microsoft/Dynamics-AX-Integration#33]
I am getting the following error while trying import from the Console App and LogicApp samples.

The console app throws the following error..
{"Message":"No HTTP resource was found that matches the request URI 'https://mydevaos.cloudax.dynamics.com/data/DataManagementDefinitionGroups/Microsoft.Dynamics.DataEntities.GetAzureWriteUrl'. No route data was found for this request."}

Logic App throws the following error..
{
    "statusCode": 400,
    "headers": {
        "Pragma": "no-cache",
        "x-ms-request-id": "09a0df9c-3538-433b-9390-8146f4cad4dd",
        "Timing-Allow-Origin": "*",
        "Cache-Control": "no-cache",
        "Date": "Thu, 31 Aug 2017 11:43:33 GMT",
        "X-AspNet-Version": "4.0.30319",
        "X-Powered-By": "ASP.NET",
        "Content-Length": "184",
        "Content-Type": "application/json; charset=utf-8",
        "Expires": "-1"
    },
    "body": {
        "Message": "Procedure: 'DataManagementDefinitionGroups/Microsoft.Dynamics.DataEntities.GetAzureWriteUrl' is not found.\r\n clientRequestId: 09a0df9c-3538-433b-9390-8146f4cad4dd"
    }
}

Can you please help?

**Comment by serup** [comment]
Could be that the server at the URI is not setup correct

**Comment by vincentnavanade** [comment]
I have exactly the same error with LogicApps, what is the GetAzureWriteUrl? Is it something to configure in D365 ops or some custom data entity to import?

**Comment by TomekMelissa** [comment]
Make sure you are using Platform Update 5 or higher.
This method returns writable Azure blob URL where you can send a data package. It is part of the new import flow.

**Comment by vincentnavanade** [comment]
Thanks a lot, I'm currently on update 3. Time for an upgrade :)
