### ISSUE TITLE
ODataServices timeout on call to ExportToPackage

### ISSUE THREAD

**Issue by tz1pkj** [Microsoft/Dynamics-AX-Integration#39]
On calling ExportToPackage for a standard data project outputting to Excel, the call to ExportToPackage does not return immediately, but sits for a period before then timing out.  I can confirm that the job execution id has been generated and the request is processing.

![image](https://user-images.githubusercontent.com/32932028/31772644-48f35f3e-b4d8-11e7-80a4-2514c88ebaa6.png)

**Comment by srpraveenkumar** [comment]
@tz1pkj - This could be a bug in the system. Could you kindly contact support team.

**Comment by ccampora** [comment]
I confirm this. I have the same behavior using the endpoint from logic apps. The expected behavior should be to return the execution Id.
