### ISSUE TITLE
AADSTS65001: The user or administrator has not consented to use the application

### ISSUE THREAD

**Issue by mpburtt** [Microsoft/Dynamics-AX-Integration#5]
I get the following error when processing a file...

Failure processing file: CustGroupExp-Customer groups.XML.Exception : AADSTS65001: The user or administrator has not consented to use the application with ID 'a8503097-efd8-47ac-8573-1c039774c3e3'. Send an interactive authorization request for this user and resource.

How would I go about sending an interactive auth request, if that really is the solution. Any ideas @nimakms?

**Comment by laneswenka** [comment]
Hi @mpburtt you can use a console application to call authorizationContext.AcquireToken() that doesn't pass in a userCredential.  Instead it uses the aadResource string, the aadClientId string, and the Uri of your reply-url setup in AAD.  That will pop up an interactive prompt.

Unfortunately this is required unless your global admin sets up the AAD application initially.  Then consent is implied by your administrator.  They may also need to use the interactive prompt once, then everyone thereafter is granted permission.

**Comment by mpburtt** [comment]
Hi @laneswenka. I'm an AAD admin and created the application in AAD but its still asking this.

Do you have some step by step instructions or is there a blog post anywhere explaining the process of using the console application that I can follow. We've had a go at doing this already without success so there must be something fundamental that we are doing wrong.

**Comment by mpburtt** [comment]
Hi  @laneswenka 
I seem to have moved on. I modified the code for OAuthHelper.cs in the service samples to call authorizationContext.AcquireToken in the manner you suggested. It looks like this now...

            AuthenticationResult authenticationResult = authenticationContext.AcquireToken(aadResource, aadClientAppId, replyUri);

When I run the JSON console application from the service sample it does indeed pop up an interactive login dialog which lets me enter my credentials but once I enter them I get another error...

Unhandled Exception: Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS65005: The client application has requested access to resource 'https://myAOS.cloudax.dynamics.com/'. This request has failed because the client has not specified this resource in its requiredResourceAccess list.
Trace ID: 20f59f6a-9490-4c8b-880f-7dbfd803f51c
Correlation ID: 3417a1dc-88e9-4772-a153-8df01f857950

As far as I can see, the application Id in AAD is configured correctly and I have a recurring data job set up with that application Id (see attached images).

Do you have any suggestions as to where to go from here?

![azureapppermsaad](https://cloud.githubusercontent.com/assets/19573619/16049547/011ed172-3250-11e6-86d9-168203262b3f.png)
![azureapppermsax](https://cloud.githubusercontent.com/assets/19573619/16049545/011ddf74-3250-11e6-80ab-9f921bfd66ca.png)
![ax recurring data job](https://cloud.githubusercontent.com/assets/19573619/16049546/011e071a-3250-11e6-886e-eb0ef1774e86.png)
![azureapp1](https://cloud.githubusercontent.com/assets/19573619/16049544/01186724-3250-11e6-9872-32a937c3f8c4.png)

**Comment by nimakms** [comment]
Closing since it seems like this issue was resolved.

**Comment by SecurePaaS** [comment]
How was this issue resolved?

**Comment by mpburtt** [comment]
it wasn't resolved - I got no answers to my last queries.

**Comment by RaphaelTagliani** [comment]
I ran into a similar problem, and the only issue was a trailing '/' at the end of the "active directory resource" string. Once the slash removed, it worked.

```
    public class OAuthHelper
    {
        /// <summary>
        /// Retrieves an authentication header from the service.
        /// </summary>
        /// <returns>The authentication header for the Web API call.</returns>
        public static async Task<string> GetAuthenticationHeader()
        {
            string aadTenant = WebServiceClientConfiguration.Settings.ActiveDirectoryTenant;
            string clientAppId = WebServiceClientConfiguration.Settings.ClientAppId;
            string clientKey = WebServiceClientConfiguration.Settings.ClientKey;
            string aadResource = WebServiceClientConfiguration.Settings.ActiveDirectoryResource;

            AuthenticationContext authenticationContext = new AuthenticationContext(aadTenant);
            ClientCredential clientCredential = new ClientCredential(clientAppId, clientKey);
            UserPasswordCredential upc = new UserPasswordCredential(WebServiceClientConfiguration.Settings.UserName,
                WebServiceClientConfiguration.Settings.Password);

            // ADAL includes an in memory cache, so this call will only send a message to the server if the cached token is expired.
            AuthenticationResult authenticationResult = await authenticationContext.AcquireTokenAsync(aadResource, clientAppId, upc);

            return authenticationResult.CreateAuthorizationHeader();
        }
    }
```

**Comment by RaphaelTagliani** [comment]
The matching configuration :

<webServiceClientSection
    uriString="https://xxxdevaos.cloudax.dynamics.com/"
    activeDirectoryResource="https://xxxdevaos.cloudax.dynamics.com"
    activeDirectoryTenant="https://login.windows.net/04e7-xxx-76eb6"
    clientAppId="0d69-xxx-a83df2"
    clientKey="DlexxxMyZ3Y=" 
    username="taglr@xxx.com"
    password="xxx"/>

Notice the activeDirectoryResource string : no slash at the end.

**Comment by mpburtt** [comment]
Thanks, I'll give that a try

**Comment by mchiovitti** [comment]
Hi everyone,

Any solution for this issue ?

I did the same as Raphael but without results :(.

**Comment by nimakms** [comment]
Hi @mchiovitti, Please try the following troubleshooting guide, and let us know what you find.

https://ax.help.dynamics.com/en/wiki/troubleshooting-service-authentication/

**Comment by dexnidoy** [comment]
Just in case this would help anyone, have you tried editing the manifest for your app in Azure AD?

"Applications provisioned in Azure AD are not enabled to use the OAuth2 implicit grant by default. You need to explicitly opt in."

I found this from this blog and it worked for me: http://blah.winsmarts.com/2015-4-Azure_AD_OAuth2_implicit_grant.aspx

**Comment by dexnidoy** [comment]
There is also an example here in Github describing the process of configuring your app:
https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp-dotnet-webapi

**Comment by Lynx15** [comment]
I am facing the same issue.
Did anyone solved the problem. If so, please post the solution.

Thanks in advance.

**Comment by prdpmv** [comment]
As per @Lynx15, Giving wrong Aad Tenant and Azure Auth Endpoint values in App.config also results in this error.

**Comment by jeffgreenrc** [comment]
I am connecting from C# project to Native app in azure. This native app, had delegates permission to Microsoft Dynamics ERP and azure default.

I am using latest version of API and using this for authentication and authorization:
`AuthenticationResult authenticationResult = authenticationContext.AcquireTokenAsync(aadAXResourceURL, aadClientAppId, userCredential).Result;`

With the above code I am not able to connect with new user or user who is connecting first time through my application.

If i use below code from old version:

`AuthenticationResult authenticationResult = authenticationContext.AcquireToken(azureAXResourceURL, azureADClientAppId, redirectURL);`

The above code works perfectly for new user, it displays a Consent form and after accepting, i am able to connect with new user.

My questions, is why with the new version of the API (the first approach mentioned) i am not able to authenticate or authorize or able to display a consent form.

Thanks

**Comment by srpraveenkumar** [comment]
@mpburtt : I see that you have  'https://myAOS.cloudax.dynamics.com/' as the aadResource name. Could you remove the trailing slash at the end of the resource name and try, like this  'https://myAOS.cloudax.dynamics.com', as this would be the string AAD would recognize. If this is still an issue let us know and we could do a screen share.

**Comment by urlrei** [comment]
I'm having the same issue, any other suggestions? I tried some of the options given above but I still I'm getting this error. Thanks.

**Comment by laneswenka** [comment]
If you feel you have it setup correctly, another option is to visit the Azure Portal ( portal.azure.com ) -> go to Azure Active Directory -> App Registrations -> find your app -> Required Permissions -> Grant Permissions.


A tenant admin can use this button to grant implicit access to everyone in your tenant to that application.


Regards,


_________________________________

Lane Swenka MCSE<https://www.linkedin.com/pub/lane-swenka/17/358/9a8>, MVP<http://mvp.microsoft.com/en-us/mvp/Lane%20Swenka-5001352>

CEO & Founder

Immobiliere Global, LLC.

Cell: 319.621.7837

www.immglobal.com<http://www.immglobal.com/>

<http://www.immglobal.com/>

<https://mvp.microsoft.com/en-us/PublicProfile/5001352?fullName=Lane%20Swenka>
________________________________

**Comment by ewild** [comment]
Follow laneswenka step. This still only grants permission to one user. You need to admin consent for all users. To do this you need to add `&prompt=admin_consent` to the end of your login query string (this page your redirected to to put in your credentials). Enter an ad admin credentials and it will prompt you to accept the app and its permissions. That is a onetime thing. More info here...

https://nicksnettravels.builttoroam.com/post/2017/01/24/Admin-Consent-for-Permissions-in-Azure-Active-Directory.aspx

**Comment by srpraveenkumar** [comment]
Thank you ewild, for the link. Closing the thread for now.

**Comment by ChandrachurhGhosh** [comment]
Hi, did anyone get a solution to this problem. In my case, I am using multi-tenant Azure AD. The user belongs to x.com domain and the application uses y.onmicrosoft.com domain. The user is a global administrator in y (Azure AD). Application is failing to use the native app registration and the log says "The user or administrator has not consented to use the application with ID".

**Comment by roniadmon** [comment]
> Hi, did anyone get a solution to this problem. In my case, I am using multi-tenant Azure AD. The user belongs to x.com domain and the application uses y.onmicrosoft.com domain. The user is a global administrator in y (Azure AD). Application is failing to use the native app registration and the log says "The user or administrator has not consented to use the application with ID".

did you manage to solve it? I'm facing this problem now...
