### ISSUE TITLE
How to parse the response from insert?

### ISSUE THREAD

**Issue by RobvanB** [Microsoft/Dynamics-AX-Integration#62]
I'm using the MS sample code to create a journal using OData.
I can create the header fine.
However, when the header is created, the journal number is returned in the response.
How do I get the journal number from the response?

The record is created using
resp = context.SaveChanges();

resp is of type DataServiceResponse, and contains the data in Json format (if I understand this correctly) - but I'm having trouble pulling gout the one field with the new journal ID.
How do I get the new journal ID from the response?

**Comment by tek9iner** [comment]
DataServiceResponse response = context.SaveChanges(SaveChangesOptions.PostOnlySetProperties);
            
            foreach (ChangeOperationResponse change in response)
            {
                EntityDescriptor descriptor = change.Descriptor as EntityDescriptor;

                if (descriptor != null)
                {
//change [DynamicsEntityName] to the entity you need
                    var ret_entity = descriptor.Entity as **[DynamicsEntityName]**;

//do whatever with ret_entity ... it should allow access to the populated properties of your newly inserted record          
                }
            }

**Comment by RobvanB** [comment]
Perfect, thanks!
