### ISSUE TITLE
OdataConsoleApplication error when calling ReadLegalEntities

### ISSUE THREAD

**Issue by vincentnavanade** [Microsoft/Dynamics-AX-Integration#66]
Hi,
I'm using Odata client 6.15 and D365FO application version 8.0.
When calling method ReadLegalEntities I am getting an error on line foreach (var legalEntity in d365.LegalEntities.AsEnumerable()):

System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=The key property 'AliasType' on for type 'ODataUtility.Microsoft.Dynamics.DataEntities.LedgerAccountAlias' is of type 'System.Nullable`1[[ODataUtility.Microsoft.Dynamics.DataEntities.DimensionAliasType, ODataUtility, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]', which is not a simple type. Only properties of simple type can be key properties.

I am able to get the total number of legal entities or vendors but I can't loop through the IEnumerable to get legal entity names.
Any ideas?

Cheers,
Vincent

**Comment by tek9iner** [comment]
What version of the OData v4 Client Code Generator extension are you using?  I had a similar issue happen to me for an entity that had an enum as part of its key definition.  I ended up upgrading the client template extension to 7.4.4 and then I was able to enumerate that entity.  

Before the update I had to go into my metadata and edit that key definition to remove that property and then I was able to loop through it after regenerating the class definitions.

**Comment by vincentnavanade** [comment]
Thanks @tek9iner I tried to remove the key from metadata file but was getting a similar error for another entity LegalEntityContact... Then I tried with 7.4.4, fixed the compile error with edmxReader and I can now get the legalEntities from enumeration.
