### ISSUE TITLE
DataServiceQueryException

### ISSUE THREAD

**Issue by haudini77** [Microsoft/Dynamics-AX-Integration#7]
I am having an issue with getting data from the application. Authentication with my credentials is going fine and an authentication header is being created and sent. However, when data is being gathered from AX an unauthorized exception is thrown:

foreach (var legalEntity in context.LegalEntities.AsEnumerable())
                {
                    Console.WriteLine("Name: {0}", legalEntity.Name);
                }

an error is being thrown - Exception thrown: 'Microsoft.OData.Client.DataServiceQueryException' in Microsoft.OData.Client.dll

Inner Exception details - 

Exception thrown: 'Microsoft.OData.Client.DataServiceQueryException' in Microsoft.OData.Client.dll
Microsoft.OData.Client.DataServiceClientException: Unauthorized
   at Microsoft.OData.Client.QueryResult.ExecuteQuery()
   at Microsoft.OData.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)

Any ideas of a solution to this please?

Thanks,
Matt

**Comment by haudini77** [comment]
Inner Exception details - 

Exception thrown: 'Microsoft.OData.Client.DataServiceQueryException' in Microsoft.OData.Client.dll
Microsoft.OData.Client.DataServiceClientException: Unauthorized
   at Microsoft.OData.Client.QueryResult.ExecuteQuery()
   at Microsoft.OData.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)

**Comment by nimakms** [comment]
Can you please share more information about the unauthorized response? You can capture the response details using Fiddler tracing tool. 
Also if you are running on a one-box environment, you can get more information from the Event Viewer under Microsoft\Dynamics\AX-IntegrationCommon\Operational, Microsoft\Dynamics\AX-SystemRuntime\Operational and Microsoft\Dynamics\AX-ApplicationServices\Operational.

**Comment by nimakms** [comment]
Closing issue since there was no response.

**Comment by gcmahi5533** [comment]
I have same issue 

Event log as below 

An unauthorized request occurred. Token service url was added to the http context.

please share if you have any solution

**Comment by gcmahi5533** [comment]
In addition more information form event logs 
Microsoft\Dynamics\AX-IntegrationCommon\Operational, 
-- An unauthorized request occurred. Token service url was added to the http context.
Microsoft\Dynamics\AX-SystemRuntime\Operational
--Entry point used for calculation of user ObjectId.
Microsoft\Dynamics\AX-ApplicationServices\Operational.
--Csrf token has been created.
