### ISSUE TITLE
Unauthorized issue while running DIXFSampleSolution

### ISSUE THREAD

**Issue by KiranMandoth** [Microsoft/Dynamics-AX-Integration#8]
Hi,
I am getting the following issue while running the RecurringIntegrationApp
StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:

Any resolution to this please?

Thanks,
Kiran

**Comment by Hesel** [comment]
I'm getting the exact same response when I try to use the RecurringIntegrationApp. Not hints, or anything, just 401, Unauthorized.
I'm using a OneBox environment with admin user credentials. I can logon to the system just fine via a browser. Import/Export of files using AX7 via the browser works fine.

I've tested the app on a cloud based deployed AX7 as well, again with admin user credentials, but keep experiencing the same issue.

The log file produced by RecurringIIntegrationApp (in the failure folder) does not provide any useful insight. From debugging the application it appears that the OData authentication is going fine, but once the data needs to be enqueued to AX the Unauthorized response appears.

**Comment by Hesel** [comment]
I've been digging into the log files (via Event Viewer), and the interesting parts were:

Microsoft\Dynamics\AX-SystemRuntime\Operational:
Invalid parameter arguments passed to the method globalUserGuidCache::getUserGuid

followed shortly by

Microsoft\Dynamics\AX-IntegrationCommon\Operational:
An unauthorized request occurred and the token service url at https://login.windows.net/scales-group.com/oauth2/authorize was added to the http context in item dynamics.Session.Unauthenticated.

**Comment by Hesel** [comment]
Got it fixed with help from Nima Kamoosi:

Turns out there was a trailing slash in the "Rainier Uri" path in the App.config file. (also remember to keep the entire path in lower case).

**Comment by nimakms** [comment]
You can try running through this to see if resolved your issue: https://ax.help.dynamics.com/en/wiki/troubleshooting-service-authentication/
