### ISSUE TITLE
Update sample to support of Odata V 7.5.2

### ISSUE THREAD

**Issue by TomFrisk** [Microsoft/Dynamics-AX-Integration#85]
When is sample updated to run on Odata 7.5.2 because metadata file is to big to be handled by the current version.

**Comment by rajdil** [comment]
Hi,
You Can update Yourself by Nu Get Packages and Keep the Metadata file to a local folder as interim workaround. 

Thanks
Raj

**Comment by TomFrisk** [comment]
Found other way to solve probem
