### ISSUE TITLE
Logic app D365 FinOps connector not found

### ISSUE THREAD

**Issue by vincentnavanade** [Microsoft/Dynamics-AX-Integration#93]
After deploying the oneDrive_to_d365_logic_app, getting error 'Connector not found' for the D365 FinOps connector.

The path property seems ok
"path": "@concat('/datasets/', encodeURIComponent(encodeURIComponent(parameters('dynamicsax_instance'))),'/procedures/', encodeURIComponent(encodeURIComponent('DataManagementDefinitionGroups/Microsoft.Dynamics.DataEntities.GetAzureWriteUrl')))"

Tried to change it to "path": "/datasets/@{encodeURIComponent(encodeURIComponent(parameters('dynamicsax_instance')))}/procedures/@{encodeURIComponent(encodeURIComponent('DataManagementDefinitionGroups/Microsoft.Dynamics.DataEntities.GetAzureWriteUrl'))}"
but it didn't work.

Any reasons why it's no longer working?
![Connector not found error](https://user-images.githubusercontent.com/22015244/59248521-029e6a80-8c66-11e9-9528-70eaedad43f8.PNG)

**Comment by vincentnavanade** [comment]
It works even though connector is not found

**Comment by akhanna007** [comment]
Connector is there.
It is not editable, as it takes parameters when you create the project.
You can edit via json
